### ISSUE TITLE
Ocultar la colección de "Autoarchivo" en el community-list

### ISSUE THREAD

**Issue by FacundoAdorno** [uner-digital/DSpace#1]
Dejar preparado el mecanismo para ocultar la comunidad de Autoarchivo en la vista de comunidades y colecciones (**/community-list**). Realizarlo para el tema _Mirage2_.

Utlizar la variable "handle-autoarchive" definida en el el archivo de constantes.

Fijarse lo realizado en  [863b3aea16607196a41d855de0a207392247e924](https://github.com/uner-digital/DSpace/commit/863b3aea16607196a41d855de0a207392247e924)

**Comment by FacundoAdorno** [comment]
@PabloDeAlbu el numero correcto de trac para el commit 863b3aea16607196a41d855de0a207392247e924 es el -#3216.

**Comment by FacundoAdorno** [comment]
@PabloDeAlbu acordate también que hay que ocultarla de la vista de la comunidad que la contiene (agrego un attached para ver esto) 
[![[#1] vista_comunidad_UNER.png](https://docs.google.com/uc?id=0B9QjFAZP4Jvxei1LME4xbHN1c0U&export=download)](https://drive.google.com/file/d/0B9QjFAZP4Jvxei1LME4xbHN1c0U/view?usp=drivesdk)

**Comment by PabloDeAlbu** [comment]
Se modificaron los archivos necesarios...

Ver commit [085f46fd0a1dd21eba28f71c7ce4e9e726303ec4](https://github.com/uner-digital/DSpace/commit/085f46fd0a1dd21eba28f71c7ce4e9e726303ec4)
