### ISSUE TITLE
revisar rotación de backups de postgres

### ISSUE THREAD

**Issue by arieljlira** [uner-digital/DSpace#101]
se eliminan los backups viejos del servidor?

**Comment by FacundoAdorno** [comment]
IDEAS:

- Enviar email cuando el directorio de DB backup llegue a un tamaño X
- Conservar los ultimos X DB backups en el directorio de backup
- Clasificar los emails por 1) semana - 2) mes, conservar los ultimos X backups semanales y mensuales...
- Considerar los backups por el nombre (que incluye la fecha) y no por la fecha de modificación del archivo de backup...

**Comment by FacundoAdorno** [comment]
Se optó por un esquema de rotación a **30** días, es decir, *se eliminan aquellos backups con fecha de modificación mayor a 30 días*.

Se agregó la siguiente cronjob:
```bash
#rotación de backups de postgres (todos los dias a las 06:00hs). Se eliminan aquellos mas antiguos a 30 dias de creación
0 6 * * 1,2,3,4,5      root   find $DSPACE_BACKUP_DIR/postgres -maxdepth 1 -name "dspace_uner_db*.gz" -mtime +30 -exec rm {} \; > /dev/null
```

Mañana tengo que verificar que se haya rotado todo como es esperado...

**Comment by FacundoAdorno** [comment]
Las rotación mediante la cronjob anterior quedó funcionando correctamente.
