### ISSUE TITLE
Configurar plugin de búsqueda para Firefox

### ISSUE THREAD

**Issue by FacundoAdorno** [uner-digital/DSpace#18]
Replicar lo realizado en el commit 0d16ffdf50b3c071c0d187c88c1697959be6e4b1 pero para el tema **Mirage2**.

**Nota**: *Este plugin permite realizar búsquedas en el módulo **discovery** de uner-digital desde el navegador **Firefox***.

**Comment by arieljlira** [comment]
me parece que no es necesario para UNER.
