### ISSUE TITLE
Configurar cuenta de email en el servidor

### ISSUE THREAD

**Issue by FacundoAdorno** [uner-digital/DSpace#20]
Crear una cuenta de **correo institucional** y configurar el servidor para enviar mensajes desde esa cuenta. 

@arieljlira por favor cuando puedas pasame los datos de la cuenta. Gracias!

**Comment by arieljlira** [comment]
Pedido

**Comment by FacundoAdorno** [comment]
Ok! :+1:

**Comment by FacundoAdorno** [comment]
Se configuró temporalmente la cuenta de correo de **CIC-Digital** en la instancia de RIUNER, hasta que nos pasen los datos de acceso a una cuenta de correo institucional de UNER...

**Comment by FacundoAdorno** [comment]
El servidor SMPT de UNER tiene habilitado el puerto 587 y utiliza  STARTTLS (si no me equivoco). Para poder hacer funcionar la configuración de correo,  tuvimos que modificar las extraproperties con lo siguiente:
```
mail.extraproperties= mail.smtp.auth=true, \
                       mail.smtp.starttls.enable=true, \
                       mail.smtp.ssl.trust=smtp.uner.edu.ar
```
Utilizando la propiedad `mail.smtp.ssl.trust` (+info [aquí][1]) se pudo enviar emails desde el servidor SMTP de la UNER, a pesar de que utilice un [self-signed certificate][2]. La contra de esto es que, aparentemente, los emails llegan sin cifrar (cosa que creo es grave)...
 
![riuner_email_send](https://cloud.githubusercontent.com/assets/6214284/21528154/2df04e7e-cd0f-11e6-8b52-5edb4f6c446a.png)

> Si no utilizamos la configuración `mail.smtp.ssl.trust` la siguiente excepción salta: `Could not convert socket to TLS (javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

Utilizando esta configuración la configuración en el servidor quedaría andando...

**NOTA APARTE**
Lo que aclaro a continuación NO LO PROBÉ, pero en el caso de NO quere utilizar `mail.smtp.ssl.trust`, habría que agregar el certificado auto-firmado por el servidor SMTP de UNER al "keystore" de la JVM utilzada para ejecutar DSpace (cómo se explica en stackoverflow --> http://stackoverflow.com/a/9619478/3406552). Para conseguir el certificado habría que utilizar el siguiente comando ([fuente][3]):
```bash
echo | openssl s_client -connect 200.61.248.73:587 -servername smtp.uner.edu.ar -starttls smtp 2>&1 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /tmp/smtp_uner_cert.pem
```


  [1]: https://www.tutorialspoint.com/javamail_api/javamail_api_smtp_servers.htm
  [2]: https://en.wikipedia.org/wiki/Self-signed_certificate
  [3]: http://stackoverflow.com/a/11738568/3406552

**Comment by FacundoAdorno** [comment]
@arieljlira ya está funcionando la cuenta en RIUNER, en el comentario de arriba encontré un problema y al parecer no se están cifrando los mensajes, ¿se te ocurre que puede ser?
