### ISSUE TITLE
Ajustar estilos al diseño solicitado

### ISSUE THREAD

**Issue by arieljlira** [uner-digital/DSpace#22]
Es necesario impementar
![muestra](https://cloud.githubusercontent.com/assets/845265/20526255/13457cae-b0a2-11e6-9115-df09c97eae11.png)

usando la paleta siguiente: 
![ri_paleta](https://cloud.githubusercontent.com/assets/845265/20526254/1327bf5c-b0a2-11e6-80f5-91ecf7710633.jpg)
dónde el celeste se usa como bgcolor de los head del sidebar y el azul se usa como color de link 

Recursos:

![ri_uner_logo](https://cloud.githubusercontent.com/assets/845265/20526253/130900f8-b0a2-11e6-94c6-49887186b9e7.png)

![ri_logo](https://cloud.githubusercontent.com/assets/845265/20526257/1346a7c8-b0a2-11e6-99af-8cef435b6017.png)

![ri_fondo head](https://cloud.githubusercontent.com/assets/845265/20526258/13474700-b0a2-11e6-91c5-c7e230003f62.jpg)

**Comment by FacundoAdorno** [comment]
* Esta es la **marca actualizada** por Lucas (sin blancos)

![riunermarcasinblanco](https://cloud.githubusercontent.com/assets/6214284/20534125/b912238c-b0be-11e6-8953-06c2cc2cf335.png)

* Este es el **favicon** actualizado por Lucas 

![riunerfavicon](https://cloud.githubusercontent.com/assets/6214284/20534164/dfe623d2-b0be-11e6-88f5-7c9c7d62a991.png)
