### ISSUE TITLE
Configurar web trackers (GoogleAnalytics y BingWebMasterTools)

### ISSUE THREAD

**Issue by FacundoAdorno** [uner-digital/DSpace#23]
Configurar el repositorio para utilizar 
* GoogleAnalytics
* BingMasterTool ([leer][1])

  [1]: http://www.amitbhawani.com/blog/submit-website-bing-webmaster-tools/

**Comment by arieljlira** [comment]
Ya pedi el domino definitivo del repositorio pero todavía no me lo pasaron. 
Una vez que lo tenga creo la cuenta de GA y luego las de GWT y BWT

**Comment by arieljlira** [comment]
La url definitiva será http://repositorio.uner.edu.ar/ 
Agrego el código de seguimiento de GA en ae236ec22f0b4694abc5abd5b55841295809fcf4

GWT y BWT será responsabilidad de UNER una vez el repo se ponga en producción.
