### ISSUE TITLE
Reformular el script build.sh

### ISSUE THREAD

**Issue by arieljlira** [uner-digital/DSpace#29]
Ajustar build.sh y: 
1. sacar el código pensado para para instalación y dejar sólo para actualización
2. permitir actualizar de 2 formas: dev y prod 

la idea es que a partir de este script se pueda actualizar el dspace cada entorno. 
La instalación estará documentada en la wiki.

**Comment by FacundoAdorno** [comment]
Acordarse de agregar la ejecución de backup de bbdd  y archivos de configuración...

**Comment by FacundoAdorno** [comment]
Para la correcta ejecución del script de actualización, habría que ejecutarlo de alguna de las siguientes formas:
```bash
/bin/bash --login
./build.sh {prod|dev}
```

ó

```bash
/bin/bash --login -c "./build.sh {prod|dev}"
``` 

Tener en cuenta que si ya se está en modo "Login Shell" (por ejemplo, iniciando una sesión remota mediante `ssh`), hay que ejecutar el comando directamente como:

```bash
./build.sh {dev|prod}
``` 
para evitar errores durante la compilación.

**Comment by FacundoAdorno** [comment]
Si se entra al **servidor** mediante `ssh`, hay que ejecutar el script de actualización de la siguiente forma:
1. Cambiarse al usuario que ejecuta la actualización en el servidor:
```bash
su -l ${UPDATE_USER}
```
2. Ejecutar el script de actualización de forma sencilla:
```bash
./build.sh prod
```
ya que ya se encuentra en modo "Login Shell" (debido a la ejecución del `su -l`).
