### ISSUE TITLE
Dar permisos a UNER-ADMIN para crear comunidades padre

### ISSUE THREAD

**Issue by FacundoAdorno** [uner-digital/DSpace#40]
Un UNER-ADMIN advirtió sobre no poder crear comunidades base. ¿Daremos esta funcionalidad a un UNER-ADMIN? O sólo se lo dejamos para los Administradores del sitio. En CIC-Digital y en SEDICI un administrador no puede crear comunidades Base, si puede crear subcomunidades de las base hacia abajo en el arbol de comunidades...

**Comment by arieljlira** [comment]
No se puede.
