### ISSUE TITLE
Acomodar página de login/registro

### ISSUE THREAD

**Issue by arieljlira** [uner-digital/DSpace#50]
En el login se muestra el link de registro de usuarios de manera poco intuitiva. 
Acomodar en una caja con bg solido el aviso de registro para que quede a la derecha del form de login con un col-md-6. 
Ej 
![image](https://cloud.githubusercontent.com/assets/845265/21103366/e88f77fc-c060-11e6-94a6-3371c8f59956.png)

Al link de registro ponerle un class de botón de BS para que se vea de manera uniforme.

**Comment by PabloDeAlbu** [comment]
Faltaría cambiar la clase del botón
