### ISSUE TITLE
Configurar servidor OAI para el SNRD

### ISSUE THREAD

**Issue by arieljlira** [uner-digital/DSpace#61]
1. Definir mapeos de metadatos para cumplir con las directrices del SNRD 2015 en base a los de CIC-DIGITAL
2. crear contexto SNRD y configurar filtros
3. Configurar mapeos

**Comment by PabloDeAlbu** [comment]
**Se realizó el mapeo en OAI para SNRD.** 

Para el campo dc:rights se infiere en base a la accesibilidad de los bitstreams siguiendo el siguiente criterio:

**info:eu-repo/semantics/closedAccess:**

 - no tiene bitstreams.
 - todos sus bitstreams tienen embargo forever.

**info:eu-repo/semantics/openAccess**
 - no tiene bitstreams con embargo.

**info:eu-repo/semantics/restrictedAccess**
 - tiene al menos un embargo forever (pero no todos).

**info:eu-repo/semantics/**
 - tiene al menos un embargo que es una fecha.

**Comment by FacundoAdorno** [comment]
Se habilitaron en el servidor las **cronjobs** que se encargan de la optimización e importación/indexación de los nuevos items creados al índice de oai.
