### ISSUE TITLE
Revisar reportes de estadísticas

### ISSUE THREAD

**Issue by arieljlira** [uner-digital/DSpace#62]
Revisar los reportes de estadísitas de comunidades, colecciones e items. 
Deben exponer sólo los resultados UTILES con charts. Ocultar los datos de ciudad porque no son confiables.

**Comment by FacundoAdorno** [comment]
![estadisticas_big_device](https://cloud.githubusercontent.com/assets/6214284/23525553/9faf3d64-ff6d-11e6-8c6e-9552dbe3f610.png)
![estadisticas_small_device](https://cloud.githubusercontent.com/assets/6214284/23525554/9fb06ffe-ff6d-11e6-99b8-99927be488ec.png)
