### ISSUE TITLE
Aplicar configuración de logrotate como en CIC-DIGITAL

### ISSUE THREAD

**Issue by arieljlira** [uner-digital/DSpace#64]

**Comment by FacundoAdorno** [comment]
Ya se creó la configuración de logrotate para DSpace como en CIC-Digital. Probé que las configuración funcionen correctamente ejecutando `sudo logrotate -f /etc/logrotate.d/dspace` y todo parece andar bien. También me fijé en el archivo `/var/lib/logrotate/status` y aparecen los archivos configurados para rotar correctamente.
