### ISSUE TITLE
En la vista completa del item no se muestra label de embargo

### ISSUE THREAD

**Issue by PabloDeAlbu** [uner-digital/DSpace#75]
Cuando una accede a la vista completa del item, se muestra un listado de los bitstreams (embargados o no) asociados al item. Si bien no es posible acceder cuando el item está embargado, estaría bueno que aparezca el label EMBARGADO como sí pasa en la vista simple del item (ver #49).

![vista_completa_item](https://cloud.githubusercontent.com/assets/6214284/22936111/42b01708-f2b3-11e6-8f2a-6bcb3d169723.png)

**Comment by FacundoAdorno** [comment]
Se corrigió la visualización de embargo en la vista completa del item.
![fulltext_embargoed](https://cloud.githubusercontent.com/assets/6214284/22940623/4e9e1962-f2c1-11e6-8f8a-78d84a58ce96.png)
