### ISSUE TITLE
PROPUESTA: Extender sintaxis del archivo de Google Scholar

### ISSUE THREAD

**Issue by FacundoAdorno** [uner-digital/DSpace#80]
Actualmente, el archivo `google-metadata.properties` permite una sintaxis que puede ser un poco limitada. Por ejemplo, hay campos como los siguientes:
* google.citation_doi
* google.citation_pmid (Pubmed ID)
* google.citation_issn
* google.citation_isbn

que no pueden mapearse con un metadato directo en RIUNER, ya que el metadato que mantiene la información de identificadores "secundarios" (alternativos al *handle*) es **dcterms.identifier**. Los bibliotecarios podría cargar los valores, por ejemplo, utilizando alguna sintaxis como la siguiente: `doi:10.1002/0470841559.ch1 ` o `issn:0395-2037`, y con el mecanismo actual que provee este modulo de GoogleScholar no se permite mapear un metadato basándonos en su valor...

También existe otro problema, y es que no se puede indicar seleccionar la autoridad de un metadato en vez de su valor. Por ejemplo: parece que Google Scholar espera que en el metadato `citation_language` se ponga un código de idioma segun alguna normativa ISO (p.e. ISO 639-1), sin embargo, RIUNER tiene como valor del metadato **dcterms.language** un *label* y en su authority tiene el *codigo ISO*.

Propongo 2 posibles **mejoras** para esta utilidad:
1. Agregar sintaxis para permitir la **selección de authority** de un metadato en lugar de su valor.
2. Agregar sintaxis para permitir el **mapeo de un metadato según su valor**. P.e.:
> google.citation_doi = dcterms.identifier:doi*

**Comment by arieljlira** [comment]
Quizás para CIC-DIGITAL en algun momento  ...
