### ISSUE TITLE
Quitar todos los placeholder y usar el hint del <field>

### ISSUE THREAD

**Issue by PabloDeAlbu** [uner-digital/DSpace#9]
Los fields asociados a un empty authority, tenian asociado un placeholder que imprimio en el input "Descripción del recurso".

¿Lo dejamos?¿Lo sacamos?¿Le agregamos un placeholder a todos los inputs?

**MODIFICACIÓN:**

1. Eliminar los placeholders que se aplican.
2. Poner una sugerencia modificando el `<hint>` de los `<fields>` involucrados:
* dcterms.isPartOf.project
* dcterms.relation.dataset
* dcterms.relation

**Comment by FacundoAdorno** [comment]
Se tendría que analizar si conviene poner un placeholder en los <fields> del formulario donde ahora se espera como valor una URL, y poner un placeholder que diga _"Ingrese enlace al recurso"_ o algo así...

**Comment by arieljlira** [comment]
Me parece mejor dejar el comportamiento default

**Comment by FacundoAdorno** [comment]
Ari, ¿no convendría poner una pista a los usuarios en los campos donde se espera un URL cruda?  Como por ejemplo: *dcterms.isPartOf.project, dcterms.isPartOf.dataset, dcterms.relation*

**Comment by arieljlira** [comment]
Si, y para eso también se puede usar el hint

**Comment by FacundoAdorno** [comment]
Entonces modificamos el hint derecho indicando que se tiene que escribir una URL en el caso de que se tenga.

**Comment by PabloDeAlbu** [comment]
Se modificó solo el hint para dcterms.relation.dataset ya que los que se habían definido en la planilla de metadatos estaban bastante completos.

**Comment by FacundoAdorno** [comment]
Con Pablo nos pusimos a dudar sobre cómo vamos a hacer con el metadato *dcterms.isPartOf.project* ya que supuestamente tendría que ir un ID pero tambien una URL... Quizás la idea de un Placeholde en este caso sea correcta
