### ISSUE TITLE
Revisar exclusiones del set SNRD

### ISSUE THREAD

**Issue by arieljlira** [uner-digital/DSpace#90]
Debe excluirse del setSNRD  todo registro 
- access=closedAccess 
- sin licencia de USO
- version=preprint
- types no autorizados
- sin metadatos obligatorios: author, date,title. que más?

**Comment by PabloDeAlbu** [comment]
Para implementar el caso de access=closed sería necesario hacer un _filter_ que consulte a solr por aquellos items:
1. sin bitstreams, o 
2. con todos sus bitstreams sin acceso para anonymous. 

El problema es que esta información se encuentra sólo en el campo item.compile (un string con el xml que representa el item) el cual se carga sólo luego de procesar individualmente cada ítem, lo que incluso puede causar que item.compile esté vacío.

Además, es de esperar que no sucedan casos como 1) o 2) ya que no serían lógicos para un repositorio institucional con política de acceso Abierto. 
Por lo anterior, se descarta el filtro por access .

**Comment by PabloDeAlbu** [comment]
Se excluyeron del set SNRD items sin idioma, licencia, titulo, autor, sin director (para cuando el type es Tesis) y con versión enviada (preprint). Para dc:identifier y dc:date siempre existen metadatos (agregados por el sistema).
