### ISSUE TITLE
Cargar items de prueba para OAI

### ISSUE THREAD

**Issue by PabloDeAlbu** [uner-digital/DSpace#92]
Cargar items para probar el OAI. Crear una comunidad de prueba que contenga una colección donde agregar esos items. Los nuevos items serán importados desde cic digital.

**Comment by PabloDeAlbu** [comment]
Se creo la comunidad "Items CIC de prueba" con la colección "Artículos, Informes y presentaciones en Congresos" con handle 123456789/90.

Para importar hacer los siguiente.

1. Cambiar en local_custom.cfg con lo siguiente (luego reiniciar tomcat)

       - authority.required.dc.type = true
       + authority.required.dc.type = false

       - authority.required.dc.type = true
       + authority.required.dcterms.language = false

       - authority.required.dcterms.accessRights = true
       + authority.required.dcterms.accessRights = false

2. Importar el siguiente [archivo][1] desde consola ejecutando

       ./dspace metadata-import -f /[ubicación del archivo descargado]/import.csv -e [uner user]

3. Ejecutar la siguiente consulta para agregar authorities que no se pudieron importar

       UPDATE metadatavalue set authority='uner:types/articulo', confidence = 600  WHERE metadata_field_id = 72 AND text_value='Artículo' and authority IS NULL;
       UPDATE metadatavalue set authority='uner:types/articulo/revision', confidence = 600 WHERE metadata_field_id = 72 AND text_value='Revisión' and authority IS NULL;
       UPDATE metadatavalue set authority='uner:types/documento_conferencia', confidence = 600  WHERE metadata_field_id = 72 AND text_value='Documento de conferencia' and authority IS NULL;

4. Volver a los valores previos en local_custom.cfg (y reiniciar tomcat)


  [1]: https://drive.google.com/open?id=0B9qynuiLjIicZ1oyeURRa1lIR2c

**Comment by PabloDeAlbu** [comment]
[import.txt](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/import-7ef1833e3608b93e4cfe1aae5f04ba4c83b1e6ba82a8e5f6638be4f981c10610.txt)

cambiar extension a csv antes de importar

**Comment by arieljlira** [comment]
Se importaron 139 registros SIN pdf en la coleccion de prueba http://uner.sedici.unlp.edu.ar/handle/123456789/90 

La validación del SNRD muestra sólo los errores esperables. 
 
```
dspace_uner_db=# UPDATE metadatavalue set authority='uner:types/articulo', confidence = 600  WHERE metadata_field_id = 72 AND text_value='Artículo' and authority IS NULL;
UPDATE 23
dspace_uner_db=# UPDATE metadatavalue set authority='uner:types/articulo/revision', confidence = 600 WHERE metadata_field_id = 72 AND text_value='Revisión' and authority IS NULL;
UPDATE 1
dspace_uner_db=# UPDATE metadatavalue set authority='uner:types/documento_conferencia', confidence = 600  WHERE metadata_field_id = 72 AND text_value='Documento de conferencia' and authority IS NULL;
UPDATE 115
```
