### ISSUE TITLE
Corregir tildes en displayed values de tipos

### ISSUE THREAD

**Issue by PabloDeAlbu** [uner-digital/DSpace#93]
Corregir tildes de los diplayed values de tipos. Si un tipo se escribe con tilde, este debe aparecer en el display value pero NO en el stored value.

**Comment by PabloDeAlbu** [comment]
@arieljlira 
Correr la siguiente consulta para normalizar los valores en la base de datos.

    UPDATE metadatavalue set text_value='Fotografía' WHERE metadata_field_id = 72 AND (text_value='fotografía' OR text_value='fotografia' OR text_value='Fotografia');
    UPDATE metadatavalue set text_value='Comunicación' WHERE metadata_field_id = 72 AND (text_value='comunicacion' OR text_value='comunicación' OR text_value='Comunicacion');
    UPDATE metadatavalue set text_value='Contribución a revista' WHERE metadata_field_id = 72 AND (text_value='contribucion a revista' OR text_value='contribución a revista' OR text_value='Contribucion a revista');
    UPDATE metadatavalue set text_value='Revisión' WHERE metadata_field_id = 72 AND (text_value='revisión' OR text_value='revision' OR text_value='Revision');
    UPDATE metadatavalue set text_value='Trabajo final de grado' WHERE metadata_field_id = 72 AND (text_value='Trabajo final de Grado');
    UPDATE metadatavalue set text_value='Documento institucional' WHERE metadata_field_id = 72 AND (text_value='Documento Institucional');
    UPDATE metadatavalue set text_value='Resolución' WHERE metadata_field_id = 72 AND (text_value='resolución' OR text_value='resolucion' OR text_value='Resolucion');
    UPDATE metadatavalue set text_value='Material de aprendizaje' WHERE metadata_field_id = 72 AND (text_value='Material de Aprendizaje');

**Comment by arieljlira** [comment]
Listo.
```
dspace_uner_db=# UPDATE metadatavalue set text_value='Fotografía' WHERE metadata_field_id = 72 AND (text_value='fotografía' OR text_value='fotografia' OR text_value='Fotografia');
UPDATE 0
dspace_uner_db=# UPDATE metadatavalue set text_value='Comunicación' WHERE metadata_field_id = 72 AND (text_value='comunicacion' OR text_value='comunicación' OR text_value='Comunicacion');
UPDATE 0
dspace_uner_db=# UPDATE metadatavalue set text_value='Contribución a revista' WHERE metadata_field_id = 72 AND (text_value='contribucion a revista' OR text_value='contribución a revista' OR text_value='Contribucion a revista');
UPDATE 0
dspace_uner_db=# UPDATE metadatavalue set text_value='Revisión' WHERE metadata_field_id = 72 AND (text_value='revisión' OR text_value='revision' OR text_value='Revision');
UPDATE 0
dspace_uner_db=# UPDATE metadatavalue set text_value='Trabajo final de grado' WHERE metadata_field_id = 72 AND (text_value='Trabajo final de Grado');
UPDATE 0
dspace_uner_db=# UPDATE metadatavalue set text_value='Documento institucional' WHERE metadata_field_id = 72 AND (text_value='Documento Institucional');
UPDATE 0
dspace_uner_db=# UPDATE metadatavalue set text_value='Resolución' WHERE metadata_field_id = 72 AND (text_value='resolución' OR text_value='resolucion' OR text_value='Resolucion');
UPDATE 1
dspace_uner_db=# UPDATE metadatavalue set text_value='Material de aprendizaje' WHERE metadata_field_id = 72 AND (text_value='Material de Aprendizaje');
UPDATE 0
```

**Comment by PabloDeAlbu** [comment]
Se corrigieron tildes y mayusculas de mas en input-form y se normalizó contenido de la base de datos.
