### ISSUE TITLE
Revisar vista de modificar item

### ISSUE THREAD

**Issue by PabloDeAlbu** [uner-digital/DSpace#94]
La vista de modificación del item es confusa. 

Ver botón "Lookup" para authority.
Se confunden el botón modificar y el agregar item
Puede resultar confuso la forma en que se eliminan los metadatos tildando un checkbox del cual se pierde la referencia del label eliminar si se scrollea mucho (agregar al lado un icono de eliminar? algo así)

**Comment by FacundoAdorno** [comment]
Relacionado con #76.
