### ISSUE TITLE
No funciona la configuración jerárquica de workflow para colecciones en subcomunidades

### ISSUE THREAD

**Issue by FacundoAdorno** [uner-digital/DSpace#97]
Luego de la etapa de muestra del servidor en el curso de febrero, detectamos que el mapeo para colecciones en colecciones de subcomunidades bajo una comunidad padre (Facultad) no está funcionando correctamente, es decir, **cuando se realiza el envío se activa el workflow de comunidad dependiente**.

CASO DONDE FUNCIONA:
![uner_wfw_exito](https://cloud.githubusercontent.com/assets/6214284/23659919/84e5af4c-0326-11e7-9072-5c38c4d7640e.png)

CASO DONDE FALLA:
![uner_wfw_error](https://cloud.githubusercontent.com/assets/6214284/23659936/96b93e00-0326-11e7-91b6-f529d27acf5e.png)

Puede ser que este problema este pasando porque esté mal puesto el atributo 'handle' en los mapeos de workflow.xml, o algun error en el código introducido en #4...

**Comment by FacundoAdorno** [comment]
Luego de revisar la propuesa de @nesovi en [DS-1519](https://jira.duraspace.org/browse/DS-1519), me di cuenta que el nombre del atributo 'collection' no tiene nada que ver con el problema: siempre se mapeará de forma jerárquica cuando se busque cual workflow corresponde a un item enviado.

Poner los siguiente:
```xml
 <!-- Mapeo temporal para Comunidad de Capacitación de UNER -->
 <name-map collection="123456789/41" workflow="comm_workflow_independiente"/>
```
es lo mismo que poner:
```xml
 <!-- Mapeo temporal para Comunidad de Capacitación de UNER -->
 <name-map handle="123456789/41" workflow="comm_workflow_independiente"/>
```

Ésto me llevó a inspeccionar el código introducido en 59a16816c50cbd33cea5157a983f116119a02925. En particular, este código está bien, simplemente parece que el error es que, desde el refactoring de based-service-api en 54222f3c1d3c63bd03af263703a950e9cfad7439, el método [getCommunities()](https://github.com/uner-digital/DSpace/blame/28a2476848392b292084abc495ddc2454047b4ac/dspace-api/src/main/java/org/dspace/content/Collection.java#L264-L267) de una Collection cambió y solo retorno una única comunidad: la comunidad padre. Sin embargo, antes retornaba todas las comunidades ancestras.

**Comment by arieljlira** [comment]
Efectivamente en DSpace 5.x el método getCommunities retornaba la cadena de padres hacia arriba de una collection [https://github.com/DSpace/DSpace/blob/dspace-5_x/dspace-api/src/main/java/org/dspace/content/Collection.java#L1431] 

Luego en DSpace 6 (https://github.com/DSpace/DSpace/blob/dspace-6_x/dspace-api/src/main/java/org/dspace/content/Collection.java#L264) cambiaron el método para que retorne sólo los padres directos de una collection (que en realidad es 1).

En el PR https://github.com/DSpace/DSpace/pull/1319 del ticket DS-2996, cambiaron las invocaciones al _community.getCommunities_ y las reemplazaron por _communityService.getAllParents(context, col);_.

Comentario del cambio de KevinVdV:
> The collection.getCommunities() method only retrieves direct parents, the old method used to retrieve them all. I create a new service method on community to retrieve all parent communities from a collection. All places which use this method & didn't just retrieve the first one have been altered.

Conclusión: es un problema que sólo nos afecta a nosotros ya que el PR https://github.com/DSpace/DSpace/pull/205 nunca fue aceptado. Cambiando por _communityService.getAllParents(context, col);_ debería resolver el problema.

Tiickets relacionados
- DS-2766 [https://jira.duraspace.org/browse/DS-2766] - /rest/collections/xxx?expand=parentCommunityList only returns 1 parent community
- DS-2996 [https://jira.duraspace.org/browse/DS-2996]- Submission collection selection does not show the complete hierarchy

**Comment by FacundoAdorno** [comment]
Ahora funciona correctamente el mapeo jerárquico presentado más arriba para las comunidades *independientes* y *dependientes*.
