### ISSUE TITLE
Aplicar últimos ajustes en el frontend

### ISSUE THREAD

**Issue by arieljlira** [uner-digital/DSpace#98]
## 1. Mensaje "n items en el repo"
- [x] cambiar color por "black"
- [x] el nro debe incluir sólo los items in_archive

## 2. Replantear menu
- [x] Ocultar menu ayuda del sidebar en md
- [x] Agrega H2 "Filtrar" Arriba de los facets
- [x] Agrega H2 "Buscar" Arriba de la caja de búsqueda
- [x] cambiar radio "Buscar en RIUNER" por "en todo el repositorio"
- [x] agregar margin-left a los radio 
![image](https://cloud.githubusercontent.com/assets/845265/23668550/3cba2e7c-0340-11e7-8b7c-4b197c314896.png)
- [x] Ajustar el menu superior para que quede 
> ¿Que es RIUNER? 
>> Acerca de
>> Politicas del repositorio 

> ¿Como agregar trabajos? 
> Acceder (link al login) / Mi cuenta (con submenues)
- [x] Revisar que el menu sin loguearse quede como sigue 
![image](https://cloud.githubusercontent.com/assets/845265/23668565/44f550c6-0340-11e7-8a60-800a739876c5.png)
- [x] Revisar que el menu logueado quede 
![image](https://cloud.githubusercontent.com/assets/845265/23668593/53632d0e-0340-11e7-9449-e6d7d005cb31.png)

## 3. Además
- [x] Sacar estadísitcas del acceso público 
- [x] Ocultar caja de exploración en contexto de /discover
- [x] En la vista del item, cuanto tenes 2 o mas abstracts, se imprimen uno seguido del otro...

**Comment by PabloDeAlbu** [comment]
@arieljlira cuando uno se loguea como administrador, se tienen que mostrar muchas cosas en el navbar y si a eso le sumas que un texto largo en el breadcrumb colapsa todo.

Una alternativa puede ser sacar el breadcrumb de uno de los col del navbar y remplazarlo por la información como puede ser Como aportar, Que es Riuner y el idioma. 

El navbar quedaría como en CIC y el breadcrumb pasaria a estar afuera, un poco mas abajo.

Estando logueado:
![1.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/1-d0a70210945a2f897283036f60a6c5a6f79bcfbb19b784636a13d4e5006ca354.png)

Sin estar logueado: 

![2 anonymus.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/2%20anonymus-0997c788aa2ea9f49f730107b9b2a579a3a2f26809eb02b857db60fa2a32d3b8.png)

**Comment by arieljlira** [comment]
El otro día convenimos en: 
- sacar idioma (por ahora)
- dejar menu estadísticas visible sólo para Administrator (el acceso sigue siendo público)
de forma de liberar 2 lugares de la derecha. Además, si pensamos en 1) el usuario visitante y  en 2) el uner-admin  (o facultad-admin) creo ambos casos quedarían aceptables. El Administrator no importa mucho dado que casi no se usa.

**Comment by PabloDeAlbu** [comment]
Se acomodó el frontend como acordamos anteriormente. Faltaría corregir cuando hay mas de un abstract.
