### ISSUE TITLE
Actualizar campo text_value y authority para dc.type

### ISSUE THREAD

**Issue by PabloDeAlbu** [uner-digital/DSpace#99]
@arieljlira vamos a tener que actualizar en la base de datos el valor de los text_value y authority para dc.type ya que en la importación de items el valor del text_value es el del authority, y el valor del authority quedó vacío. Tambien aprovechamos para setear el valor de confidence.

La consulta a ejecutar es:

    UPDATE metadatavalue set text_value = 'Borrador', authority='info:eu-repo/semantics/draft', confidence = 600 WHERE metadata_field_id = 134 AND text_value='info:eu-repo/semantics/draft';
    UPDATE metadatavalue set text_value = 'Versión Publicada', authority='info:eu-repo/semantics/publishedVersion', confidence = 600 WHERE metadata_field_id = 134 AND text_value='info:eu-repo/semantics/publishedVersion';
    UPDATE metadatavalue set text_value = 'Versión aceptada', authority='info:eu-repo/semantics/acceptedVersion', confidence = 600 WHERE metadata_field_id = 134 AND text_value='info:eu-repo/semantics/acceptedVersion';
    UPDATE metadatavalue set text_value = 'Versión enviada', authority='info:eu-repo/semantics/submittedVersion', confidence = 600 WHERE metadata_field_id = 134 AND text_value='info:eu-repo/semantics/submittedVersion';
    UPDATE metadatavalue set text_value = 'Versión Actualizada', authority='info:eu-repo/semantics/updatedVersion', confidence = 600 WHERE metadata_field_id = 134 AND text_value='info:eu-repo/semantics/updatedVersion';

**Comment by arieljlira** [comment]
dspace_uner_db=# UPDATE metadatavalue set text_value = 'Borrador', authority='info:eu-repo/semantics/draft', confidence = 600 WHERE metadata_field_id = 134 AND text_value='info:eu-repo/semantics/draft';
UPDATE 0
dspace_uner_db=# UPDATE metadatavalue set text_value = 'Versión Publicada', authority='info:eu-repo/semantics/publishedVersion', confidence = 600 WHERE metadata_field_id = 134 AND text_value='info:eu-repo/semantics/publishedVersion';
UPDATE 99
dspace_uner_db=# UPDATE metadatavalue set text_value = 'Versión aceptada', authority='info:eu-repo/semantics/acceptedVersion', confidence = 600 WHERE metadata_field_id = 134 AND text_value='info:eu-repo/semantics/acceptedVersion';
UPDATE 2
dspace_uner_db=# UPDATE metadatavalue set text_value = 'Versión enviada', authority='info:eu-repo/semantics/submittedVersion', confidence = 600 WHERE metadata_field_id = 134 AND text_value='info:eu-repo/semantics/submittedVersion';
UPDATE 35
dspace_uner_db=# UPDATE metadatavalue set text_value = 'Versión Actualizada', authority='info:eu-repo/semantics/updatedVersion', confidence = 600 WHERE metadata_field_id = 134 AND text_value='info:eu-repo/semantics/updatedVersion';
UPDATE 0
